spring:
  application:
    name: microservice-order

    microservice-order:
      url: https://order.microservicesdemo.net/order/api/v1/

  data:
    mongodb:
      uri: mongodb+srv://mkmongouser:Secret_Password@cluster0.yu4x6.mongodb.net
      database: order

server:
  port: 8080
  servlet:
    context-path: /order
